### ISSUE TITLE
Deleting Checkbox

### ISSUE THREAD

**Issue by alafad** [exislow/kleinanzeigen-magic#19]
Hello, how i must change the code, that i have a checkbox for doesnt delete the old Kleinanzeige , when i will publish a second one ?
Have you a hint for me?

Thank you !

**Comment by exislow** [comment]
Hello,

sorry this idea is nonsense. Why would you like to clone your ads? Because of the view count or stars? Sorry, but this is not Instagram or any other attention seeking network. It does not matter how many stars / views your ad has as long it is not sold. This way you will just spam Kleinanzeigen. I do not support this.
