### ISSUE TITLE
Thanks and Questions

### ISSUE THREAD

**Issue by panzli** [exislow/kleinanzeigen-magic#22]
Hello,
 first of all thanks for the cool project. Will there ever be an APK? And what is the easiest way to edit the source code and recompile the program?

**Comment by exislow** [comment]
You can generate an APK using this project by yourself, since it is built with quasar (https://quasar.dev/quasar-cli-vite/developing-cordova-apps/build-commands). I do not own an Android devic, thus I cannot help here.

The easiest way is grabbing any IDE of your choice (IntelliJ, VSCode etc.), edit the code and recompile it how it is described in the `README.md` / according to the Quasar docs (quasar.dev).
